begin;

create table if not exists public.paper_portfolio_snapshots (
    id bigint generated by default as identity primary key,
    strategy_id text not null,
    bar_timestamp timestamptz not null,
    quote_timestamp timestamptz not null,
    signal_close numeric not null,
    mark_price numeric not null,
    bid numeric not null,
    ask numeric not null,
    signal text not null,
    reason text not null,
    target_position double precision not null,
    cash numeric not null,
    btc numeric not null,
    equity numeric not null,
    gross_equity numeric not null,
    cost_drag numeric not null,
    return_pct double precision not null,
    gross_return_pct double precision not null,
    drawdown double precision not null,
    peak_equity numeric not null,
    total_fees numeric not null,
    total_spread numeric not null,
    total_slippage numeric not null,
    total_turnover numeric not null,
    trade_count integer not null,
    bars_processed integer not null,
    streak_direction integer not null,
    streak_length integer not null,
    run_return_bps double precision not null,
    relative_volume double precision not null,
    body_fraction double precision not null,
    broader_trend_up integer not null,
    regime_spread_bps double precision not null default 0.0,
    momentum_bps double precision not null default 0.0,
    created_at timestamptz not null default now(),
    constraint paper_portfolio_snapshots_strategy_bar_key
        unique (strategy_id, bar_timestamp)
);

alter table public.paper_portfolio_snapshots
    add column if not exists regime_spread_bps double precision not null default 0.0;

alter table public.paper_portfolio_snapshots
    add column if not exists momentum_bps double precision not null default 0.0;

create table if not exists public.paper_trades (
    id bigint generated by default as identity primary key,
    strategy_id text not null,
    bar_timestamp timestamptz not null,
    quote_timestamp timestamptz not null,
    side text not null check (side in ('buy', 'sell')),
    btc_delta numeric not null,
    mark_price numeric not null,
    reference_price numeric not null,
    fill_price numeric not null,
    gross_notional numeric not null,
    fee numeric not null,
    spread_cost numeric not null,
    slippage_cost numeric not null,
    cash_after numeric not null,
    btc_after numeric not null,
    equity_after numeric not null,
    created_at timestamptz not null default now(),
    constraint paper_trades_strategy_bar_side_key
        unique (strategy_id, bar_timestamp, side)
);

create index if not exists paper_snapshots_bar_idx
    on public.paper_portfolio_snapshots (bar_timestamp desc);

create index if not exists paper_snapshots_strategy_bar_idx
    on public.paper_portfolio_snapshots (strategy_id, bar_timestamp desc);

create index if not exists paper_trades_bar_idx
    on public.paper_trades (bar_timestamp desc);

create or replace view public.paper_latest_status as
select distinct on (strategy_id)
    strategy_id,
    bar_timestamp,
    quote_timestamp,
    signal,
    reason,
    target_position,
    cash,
    btc,
    equity,
    gross_equity,
    cost_drag,
    return_pct,
    gross_return_pct,
    drawdown,
    total_fees,
    total_spread,
    total_slippage,
    total_turnover,
    trade_count,
    streak_direction,
    streak_length,
    run_return_bps,
    relative_volume,
    body_fraction,
    regime_spread_bps,
    momentum_bps
from public.paper_portfolio_snapshots
order by strategy_id, bar_timestamp desc;

create or replace view public.paper_strategy_performance as
select
    strategy_id,
    min(bar_timestamp) as first_snapshot,
    max(bar_timestamp) as latest_snapshot,
    max(trade_count) as trades,
    max(total_fees) as total_fees,
    max(total_spread) as total_spread,
    max(total_slippage) as total_slippage,
    min(drawdown) as max_drawdown,
    (array_agg(equity order by bar_timestamp desc))[1] as latest_equity,
    (array_agg(gross_equity order by bar_timestamp desc))[1] as latest_gross_equity,
    (array_agg(return_pct order by bar_timestamp desc))[1] as latest_return_pct,
    (array_agg(gross_return_pct order by bar_timestamp desc))[1] as latest_gross_return_pct,
    (array_agg(cost_drag order by bar_timestamp desc))[1] as latest_cost_drag
from public.paper_portfolio_snapshots
group by strategy_id;

alter table public.paper_portfolio_snapshots enable row level security;
alter table public.paper_trades enable row level security;

-- No anon/authenticated policies are created. The server-side Supabase secret
-- key used by the bot and private Streamlit dashboard bypasses RLS.

commit;
