begin;

-- Telemetry mirror for the equity Phase-2 shadow deployment
-- (experiments/run_equity_paper_step.py). The SQLite ledger under
-- runtime/equity_*_paper.sqlite3 remains the source of truth for trading
-- decisions; this table is a best-effort remote-monitoring copy, one row per
-- run_step() invocation, uploaded via a durable local outbox so a Supabase
-- outage never blocks or corrupts the trading step.
create table if not exists public.equity_paper_runs (
    id bigint generated by default as identity primary key,
    run_id uuid not null,
    received_at timestamptz not null default now(),
    server_name text,
    data_source text not null check (data_source in ('yfinance', 'schwab')),
    config_hash text,
    started_at timestamptz not null,
    finished_at timestamptz not null,
    duration_seconds double precision,
    status text not null check (status in ('ok', 'already_processed', 'halted', 'error')),
    message text,
    as_of_date date,
    halted boolean not null default false,
    halt_reason text,
    last_processed_bar_date date,
    completed_trades integer not null default 0,
    ending_equity numeric,
    total_return double precision,
    max_drawdown double precision,
    win_rate double precision,
    open_position_symbol text,
    open_position_status text,
    open_position_entry_price numeric,
    open_position_stop_price numeric,
    open_position_target_price numeric,
    open_position_predicted_return double precision,
    constraint equity_paper_runs_run_id_key unique (run_id)
);

create index if not exists equity_paper_runs_source_time_idx
    on public.equity_paper_runs (data_source, received_at desc);

create or replace view public.equity_paper_latest_status as
select distinct on (data_source)
    data_source,
    received_at,
    status,
    message,
    as_of_date,
    halted,
    halt_reason,
    last_processed_bar_date,
    completed_trades,
    ending_equity,
    total_return,
    max_drawdown,
    win_rate,
    open_position_symbol,
    open_position_status
from public.equity_paper_runs
order by data_source, received_at desc;

alter table public.equity_paper_runs enable row level security;

-- No anon/authenticated policies are created. The server-side Supabase secret
-- key used by the paper step (and, later, the dashboard) bypasses RLS.

commit;
